version: 0.0
os: linux
files:
  - source: /dist
    destination: /var/www/html/msf-develop
hooks:
  BeforeInstall:
    - location: scripts/aws_deploy.sh
  # AfterInstall:
  #   - location: Scripts/RunResourceTests.sh
  #     timeout: 180
  # ApplicationStart:
  #   - location: Scripts/RunFunctionalTests.sh
  #     timeout: 3600
  # ValidateService:
  #   - location: Scripts/MonitorService.sh
  #     timeout: 3600
  #     runas: codedeployuser