export const AVAILABLE_LAYER_LIST_LOADING = "AVAILABLE_LAYER_LIST_LOADING";
export const AVAILABLE_LAYER_LIST_LOADED = "AVAILABLE_LAYER_LIST_LOADED";

export const SET_LAYER_SIDEBAR_CATEGORY = "SET_LAYER_SIDEBAR_CATEGORY";
export const CHANGE_LAYER_SIDEBAR_CATEGORY = "CHANGE_LAYER_SIDEBAR_CATEGORY";
export const UPDATE_AVAILABLE_FEATURE_LIST = "UPDATE_AVAILABLE_FEATURE_LIST";

export const FEATURE_SIDEBAR_PAGE_FORWARD = "FEATURE_SIDEBAR_PAGE_FORWARD";
export const FEATURE_SIDEBAR_PAGE_BACKWARD = "FEATURE_SIDEBAR_PAGE_BACKWARD";

export const UPDATE_ACTIVE_SUBCATEGORIES = "UPDATE_ACTIVE_SUBCATEGORIES";
export const REFRESH_ACTIVE_SUBCATEGORIES = "REFRESH_ACTIVE_SUBCATEGORIES";

export const UPDATE_FEATURE_DETAIL = "UPDATE_FEATURE_DETAIL";
export const FEATURE_DETAIL_INFO_LOADING = "FEATURE_FOCUS_INFO_LOADING";
export const FEATURE_DETAIL_INFO_LOADED = "FEATURE_FOCUS_INFO_LOADED";
export const UPDATE_FEATURE_DETAIL_INFO = "UPDATE_FEATURE_FOCUS_INFO";
export const HIDE_FEATURE_FOCUS_CONTAINER = "HIDE_FEATURE_FOCUS_CONTAINER";

export const UPDATE_FEATURE_SEARCH_TEXT = "UPDATE_FEATURE_SEARCH_TEXT";
export const UPDATE_FEATURE_SEARCH_RESULTS = "UPDATE_FEATURE_SEARCH_RESULTS";

export const TOGGLE_INFRASTRUCTURE_FACILITY_FILTER_OPTIONS_VISIBLE =
	"TOGGLE_INFRASTRUCTURE_FACILITY_FILTER_OPTIONS_VISIBLE";

export const SET_GROUP_LAYER_ACTIVE = "SET_GROUP_LAYER_ACTIVE";
export const SET_GROUP_ACTIVE = "SET_GROUP_ACTIVE";
