export const AVAILABLE_LAYER_LIST_LOADING = "AVAILABLE_LAYER_LIST_LOADING";
export const AVAILABLE_LAYER_LIST_LOADED = "AVAILABLE_LAYER_LIST_LOADED";

export const SET_LAYER_SIDEBAR_CATEGORY = "SET_LAYER_SIDEBAR_CATEGORY";
export const CHANGE_LAYER_SIDEBAR_CATEGORY = "CHANGE_LAYER_SIDEBAR_CATEGORY";
export const UPDATE_AVAILABLE_FEATURES = "UPDATE_AVAILABLE_FEATURES";

export const FEATURE_SIDEBAR_PAGE_FORWARD = "FEATURE_SIDEBAR_PAGE_FORWARD";
export const FEATURE_SIDEBAR_PAGE_BACKWARD = "FEATURE_SIDEBAR_PAGE_BACKWARD";

export const UPDATE_ACTIVE_SUBCATEGORIES = "UPDATE_ACTIVE_SUBCATEGORIES";

export const UPDATE_FEATURE_DETAIL = "UPDATE_FEATURE_DETAIL";
export const FEATURE_DETAIL_INFO_LOADING = "FEATURE_DETAIL_INFO_LOADING";
export const FEATURE_DETAIL_INFO_LOADED = "FEATURE_DETAIL_INFO_LOADED";
export const HIDE_FEATURE_DETAIL = "HIDE_FEATURE_DETAIL";

export const UPDATE_FEATURE_SEARCH_TEXT = "UPDATE_FEATURE_SEARCH_TEXT";
export const UPDATE_FEATURE_SEARCH_RESULTS = "UPDATE_FEATURE_SEARCH_RESULTS";

export const TOGGLE_INFRASTRUCTURE_FACILITY_FILTER_OPTIONS_VISIBLE =
    "TOGGLE_INFRASTRUCTURE_FACILITY_FILTER_OPTIONS_VISIBLE";

export const SET_GROUP_LAYER_ACTIVE = "SET_GROUP_LAYER_ACTIVE";
export const SET_GROUP_ACTIVE = "SET_GROUP_ACTIVE";

export const SET_PLUME_DATE_RANGE = "SET_PLUME_DATE_RANGE";
export const UPDATE_FLIGHT_CAMPAIGN = "UPDATE_FLIGHT_CAMPAIGN";
export const UPDATE_IME = "UPDATE_IME";

export const CENTER_MAP_ON_POINT = "CENTER_MAP_ON_POINT";
export const CENTER_MAP_ON_FEATURE = "CENTER_MAP_ON_FEATURE";
export const TOGGLE_FEATURE_LABEL = "TOGGLE_FEATURE_LABEL";
export const CLEAR_FEATURE_LABELS = "CLEAR_FEATURE_LABELS";
export const SELECT_FEATURE_IN_SIDEBAR = "SELECT_FEATURE_IN_SIDEBAR";
