export const AVAILABLE_LAYER_LIST_LOADING = "AVAILABLE_LAYER_LIST_LOADING";
export const AVAILABLE_LAYER_LIST_LOADED = "AVAILABLE_LAYER_LIST_LOADED";

export const SET_LAYER_SIDEBAR_CATEGORY = "SET_LAYER_SIDEBAR_CATEGORY";
export const SET_LAYER_SIDEBAR_COLLAPSED = "SET_LAYER_SIDEBAR_COLLAPSED";
export const CHANGE_LAYER_SIDEBAR_CATEGORY = "CHANGE_LAYER_SIDEBAR_CATEGORY";
export const UPDATE_AVAILABLE_FEATURES = "UPDATE_AVAILABLE_FEATURES";

export const FEATURE_SIDEBAR_PAGE_FORWARD = "FEATURE_SIDEBAR_PAGE_FORWARD";
export const FEATURE_SIDEBAR_PAGE_BACKWARD = "FEATURE_SIDEBAR_PAGE_BACKWARD";

export const UPDATE_ACTIVE_SUBCATEGORIES = "UPDATE_ACTIVE_SUBCATEGORIES";

export const UPDATE_FEATURE_DETAIL = "UPDATE_FEATURE_DETAIL";
export const FEATURE_DETAIL_INFO_LOADING = "FEATURE_DETAIL_INFO_LOADING";
export const FEATURE_DETAIL_INFO_LOADED = "FEATURE_DETAIL_INFO_LOADED";
export const HIDE_FEATURE_DETAIL = "HIDE_FEATURE_DETAIL";
export const VISTA_METADATA_LOADING = "VISTA_METADATA_LOADING";
export const UPDATE_VISTA_METADATA = "UPDATE_VISTA_METADATA";

export const UPDATE_FEATURE_SEARCH_TEXT = "UPDATE_FEATURE_SEARCH_TEXT";
export const UPDATE_FEATURE_SEARCH_RESULTS = "UPDATE_FEATURE_SEARCH_RESULTS";

export const TOGGLE_INFRASTRUCTURE_FACILITY_FILTER_OPTIONS_VISIBLE =
    "TOGGLE_INFRASTRUCTURE_FACILITY_FILTER_OPTIONS_VISIBLE";

export const SET_GROUP_LAYER_ACTIVE = "SET_GROUP_LAYER_ACTIVE";
export const SET_GROUP_ACTIVE = "SET_GROUP_ACTIVE";

// export const SET_PLUME_DATE_RANGE = "SET_PLUME_DATE_RANGE";
// export const UPDATE_FLIGHT_CAMPAIGN = "UPDATE_FLIGHT_CAMPAIGN";
// export const UPDATE_IME = "UPDATE_IME";
export const SET_PLUME_FILTER = "SET_PLUME_FILTER";
export const SET_INFRASTRUCTURE_FILTER = "SET_INFRASTRUCTURE_FILTER";

export const RESIZE_MAP = "RESIZE_MAP";
export const CENTER_MAP_ON_POINT = "CENTER_MAP_ON_POINT";
export const CENTER_MAP_ON_FEATURE = "CENTER_MAP_ON_FEATURE";
export const TOGGLE_FEATURE_LABEL = "TOGGLE_FEATURE_LABEL";
export const CLEAR_FEATURE_LABELS = "CLEAR_FEATURE_LABELS";
export const SELECT_FEATURE_IN_SIDEBAR = "SELECT_FEATURE_IN_SIDEBAR";

export const SET_HOVER_PLUME = "SET_HOVER_PLUME";

export const AVAILABLE_GRIDDED_DATES_LOADING = "AVAILABLE_GRIDDED_DATES_LOADING";
export const UPDATE_AVAILABLE_GRIDDED_DATES = "UPDATE_AVAILABLE_GRIDDED_DATES";
export const UPDATE_GRIDDED_DATE = "UPDATE_GRIDDED_DATE";
export const INCREMENT_GRIDDED_DATE = "INCREMENT_GRIDDED_DATE";

export const UPDATE_FEATURE_PICKER = "UPDATE_FEATURE_PICKER";
export const SET_ACTIVE_PICKER_FEATURE = "SET_ACTIVE_PICKER_FEATURE";

export const CHANGE_PLUME_CHART_MODE = "CHANGE_PLUME_CHART_MODE";
export const TOGGLE_PLUMES_WITH_OBSERVATIONS_ONLY = "TOGGLE_PLUMES_WITH_OBSERVATIONS_ONLY";
export const CHANGE_INFRASTRUCTURE_CHART_MODE = "CHANGE_INFRASTRUCTURE_CHART_MODE";
export const SET_PLUME_SOURCE_FILTER = "SET_PLUME_SOURCE_FILTER";
export const SET_FLYOVER_FILTER = "SET_FLYOVER_FILTER";
export const FEATURE_DETAIL_PLUME_LIST_LOADING = "FEATURE_DETAIL_PLUME_LIST_LOADING";
export const UPDATE_FEATURE_DETAIL_PLUME_LIST = "UPDATE_FEATURE_DETAIL_PLUME_LIST";
export const SET_PLUME_FILTER_DATE = "SET_PLUME_FILTER_DATE";

export const CHANGE_APP_MODE = "CHANGE_APP_MODE";

export const CHANGE_ANALYTICS_MODE = "CHANGE_ANALYTICS_MODE";
export const CHANGE_ANALYTICS_FILTER_SELECTED_AREA = "CHANGE_ANALYTICS_FILTER_SELECTED_AREA";
export const CHANGE_ANALYTICS_FILTER_SELECTED_SECTOR = "CHANGE_ANALYTICS_FILTER_SELECTED_SECTOR";
export const CHANGE_ANALYTICS_FILTER_SELECTED_SUBSECTOR =
    "CHANGE_ANALYTICS_FILTER_SELECTED_SUBSECTOR";
export const CHANGE_ANALYTICS_FILTER_SELECTED_UNITS = "CHANGE_ANALYTICS_FILTER_SELECTED_UNITS";

export const UPDATE_OIL_WELLS = "UPDATE_OIL_WELLS";
export const UPDATE_ANALYTICS_SUMMARY_DATA = "UPDATE_ANALYTICS_SUMMARY_DATA";
export const ANALYTICS_SUMMARY_DATA_LOADING = "ANALYTICS_SUMMARY_DATA_LOADING";
export const UPDATE_ANALYTICS_DETECTION_STATS = "UPDATE_ANALYTICS_DETECTION_STATS";
export const ANALYTICS_DETECTION_STATS_LOADING = "ANALYTICS_DETECTION_STATS_LOADING";

export const UPDATE_AREA_SEARCH_LIST = "UPDATE_AREA_SEARCH_LIST";
export const AREA_SEARCH_LIST_LOADING = "AREA_SEARCH_LIST_LOADING";

export const SECTOR_OPTIONS_LIST_LOADING = "SECTOR_OPTIONS_LIST_LOADING";
export const UPDATE_SECTOR_OPTIONS_LIST = "UPDATE_SECTOR_OPTIONS_LIST";

export const UPDATE_ANALYTICS_EMISSIONS_SOURCE_DATA = "UPDATE_ANALYTICS_EMISSIONS_SOURCE_DATA";
export const ANALYTICS_EMISSIONS_SOURCE_DATA_LOADING = "ANALYTICS_EMISSIONS_SOURCE_DATA_LOADING";

export const CHANGE_ANALYTICS_DATE = "CHANGE_ANALYTICS_DATE";
export const UPDATE_SUMMARY_PAGE_SOURCE_INDEX = "UPDATE_SUMMARY_PAGE_SOURCE_INDEX";

export const TOGGLE_HOME_SELECT_MENU_OPEN = "TOGGLE_HOME_SELECT_MENU_OPEN";
export const SET_HOME_AREA = "SET_HOME_AREA";

export const SHOW_COOKIE_MODAL = "SHOW_COOKIE_MODAL";
export const SET_COOKIE_ACCEPT = "SET_COOKIE_ACCEPT";

export const UPDATE_INFRA_GLOBAL_RESULTS = "UPDATE_INFRA_GLOBAL_RESULTS";

export const COMPLETE_LANDING_PAGE_LOAD = "COMPLETE_LANDING_PAGE_LOAD";
export const SHOW_LOADING_CONTAINER = "SHOW_LOADING_CONTAINER";
