export const PLUME_SOURCES_LIST = 0;
export const PLUME_SOURCES_THUMB = 1;
export const PLUME_SOURCES_CHART = 2;

export const INFRASTRUCTURE_SOURCES_LIST = 0;
export const INFRASTRUCTURE_SOURCES_THUMB = 1;
export const INFRASTRUCTURE_SOURCES_CHART = 2;

export const APP_MODE_MAP = 0;
export const APP_MODE_ANALYTICS = 1;

export const ANALYTICS_MODE_PLUME_DETECTION_STATS = "ANALYTICS_MODE_PLUME_DETECTION_STATS";
export const ANALYTICS_MODE_EMISSIONS_CHARTS = "ANALYTICS_MODE_EMISSIONS_CHARTS";
export const ANALYTICS_MODE_EMISSIONS_SUMMARY_INFO = "ANALYTICS_MODE_EMISSIONS_SUMMARY_INFO";
